Arrays
bfwetmore/learningth pull request #8
Opened 2021-11-24 04:03 UTC by bfwetmore

Add rough work from Array lessons and new quiz challenge.

2021-11-25 15:05 UTC, do-work requested changes

2021-11-25 15:05 UTC, do-work commented on array's/build-a-quiz-challenge/start/css/style.css
> +* {
I don't usually see apostrophes in directory names.
I would do `arrays` instead of `array's`

2021-11-28 04:45 UTC, bfwetmore commented on array's/build-a-quiz-challenge/start/css/style.css
> +* {
done

2021-11-28 16:46 UTC, do-work approved these changes

2021-11-28 17:16 UTC, merged